#!/bin/bash

sudo yum install docker
sudo systemctl start docker
sudo systemctl enable docker
sudo groupadd docker
sudo usermod -aG docker vagrant
sudo usermod -aG docker vagrant
sudo systemctl restart docker

